version: '3.7'

services:
  aws-lambda-layers:
    build: .
    volumes:
      - './layers:/home/layers'
    working_dir: '/home/'
    command: sh -c "pip install -r layers/requirements.txt -t python/ && zip -r layers/deploy_package.zip python/"
