AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: mecab

Parameters:
  Project:
    Type: String
  Env:
    Type: String
  LambdaName:
    Type: String
  LayerName:
    Type: String
  AccountId:
    Type: String

Resources:

  # Lambda Function
  MeCabFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Env}-${Project}-${LambdaName}
      Handler: lambda_function.lambda_handler
      CodeUri: ./function
      Runtime: python3.8
      Timeout: 60
      MemorySize: 256
      Layers:
        - !Ref MeCabLayer
      Environment:
        Variables:
          LOG_LEVEL: INFO

  # Lambda Layer
  MeCabLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub ${Env}-${Project}-${LayerName}
      Content:
        S3Bucket: test-mori-python
        S3Key: !Sub deploy_package.zip
      CompatibleRuntimes:
        - python3.8
